version: '2'
services:
  web:
    image: registry-internal.cn-hangzhou.aliyuncs.com/lingmall/web

    restart: always

    ports:
      - 80

    labels:
      aliyun.rolling_updates: 'true'
      aliyun.scale: '2'
      aliyun.log_store: stdout
      aliyun.routing.port_80: web;dev-api.lingmall.com
      aliyun.routing.session_sticky: 'true'
